name: flutter_futrue
description: Use the Flutter + MVC +Refresh plugin to help you quickly develop your Flutter APP
version: 1.0.2
author: pf <133300871@qq.com>
homepage: https://github.com/android-pf

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ######
  connectivity: ^0.4.3+7
  pull_to_refresh: ^1.5.3
  ######
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.futurenavi.flutter_futrue
    pluginClass: FlutterFutruePlugin
